<?php

function add_numbers($body)
{
    if ($body === null) {
        return ['error' => 'missing input body'];
    }

    $x = filter_var($body['x'] ?? null, FILTER_VALIDATE_FLOAT);
    $y = filter_var($body['y'] ?? null, FILTER_VALIDATE_FLOAT);
    $a = filter_var($body['a'] ?? null, FILTER_VALIDATE_FLOAT);

    if ($x === false || $y === false || $a === false) {
        return ['error' => 'x, y, and a must all be numbers'];
    }

    $z = $x + $y + $a;
    $answer = $x > $y ? 'true' : 'false';

    return [$z, $answer];
}

function add_strings($body)
{
    $body = $body ?? [];

    $a = $body['a'] ?? null;
    $b = $body['b'] ?? null;
    $c = $body['c'] ?? null;
    $values = [$a, $b, $c];

    foreach ($values as $v) {
        if (!is_string($v)) {
            return ['error' => 'a, b, and c must all be strings'];
        }
    }

    foreach ($values as $v) {
        $len = strlen($v);
        if ($len <= 0 || $len > 100) {
            return ['error' => 'each word must be between 1 and 100 characters'];
        }
    }

    return ['result' => implode(' ', $values)];
}

function add_phrase($body = null)
{
    return 'This is a phrase that has been autogenerated to show string functions';
}

function string_func($body)
{
    $phrase = $body['text'] ?? '';

    $slice = substr($phrase, 0, 16);
    $upper = strtoupper($phrase);

    return [$slice, $upper];
}
