<?php
// Basic exercises: numbers, strings and string functions.
// Mirrors python-stack/app/www/scripts/basic.py. Each function takes the
// decoded JSON request body ($body) and returns an array that router.php
// turns into the JSON response.

// Adds x + y + a and says whether x > y.
// Called by the "add numbers" form on index.html with {"x": .., "y": .., "a": ..}.
function add_numbers($body)
{
    if ($body === null) {
        return ['error' => 'missing input body'];
    }

    // filter_var(..., FILTER_VALIDATE_FLOAT) returns the number, or false if it
    // isn't one -- PHP's version of Python's float() + try/except ValueError.
    // `?? null` means "use null if the key is missing" (like body.get("x")).
    $x = filter_var($body['x'] ?? null, FILTER_VALIDATE_FLOAT);
    $y = filter_var($body['y'] ?? null, FILTER_VALIDATE_FLOAT);
    $a = filter_var($body['a'] ?? null, FILTER_VALIDATE_FLOAT);

    // === checks value AND type, so 0.0 isn't mistaken for false.
    if ($x === false || $y === false || $a === false) {
        return ['error' => 'x, y, and a must all be numbers'];
    }

    $z = $x + $y + $a;
    // Ternary: condition ? value-if-true : value-if-false
    $answer = $x > $y ? 'true' : 'false';

    // A list-style array becomes a JSON array: [6, "false"]
    return [$z, $answer];
}

// Joins three words into one sentence.
// Called by the "add strings" form on index.html with {"a": .., "b": .., "c": ..}.
function add_strings($body)
{
    // If $body is null, use an empty array instead (like `body or {}` in Python).
    $body = $body ?? [];

    $a = $body['a'] ?? null;
    $b = $body['b'] ?? null;
    $c = $body['c'] ?? null;
    $values = [$a, $b, $c];

    // Every value must be a string (rejects numbers, null, lists...).
    foreach ($values as $v) {
        if (!is_string($v)) {
            return ['error' => 'a, b, and c must all be strings'];
        }
    }

    // Every word must be 1-100 characters long.
    foreach ($values as $v) {
        $len = strlen($v);
        if ($len <= 0 || $len > 100) {
            return ['error' => 'each word must be between 1 and 100 characters'];
        }
    }

    // implode = Python's " ".join(values)
    return ['result' => implode(' ', $values)];
}

// Returns a fixed sentence. A plain string becomes a JSON string.
function add_phrase($body = null)
{
    return 'This is a phrase that has been autogenerated to show string functions';
}

// Shows two string functions on the phrase above.
// Note: unlike Python's string_func, this ignores $body and uses add_phrase()
// directly -- the page sends the same phrase, so the result is identical.
function string_func($body = null)
{
    $phrase = add_phrase();

    // substr(string, start, length) = Python's phrase[0:16]
    $slice = substr($phrase, 0, 16);
    // strtoupper = Python's phrase.upper()
    $upper = strtoupper($phrase);

    // An array with string keys becomes a JSON object: {"slice": .., "upper": ..}
    return ['slice' => $slice, 'upper' => $upper];
}
